apiVersion: apps/v1
kind: Deployment
metadata:
  name: komentar-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: komentar
  template:
    metadata:
      labels:
        app: komentar
    spec:
      containers:
        - image: prelog/rso_komentar:2024-01-11-10-58-52
          name: komentar
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://ep-ancient-fog-19741782-pooler.eu-central-1.aws.neon.tech/izletnik
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: grzin
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              #value: ep2sMLqtu3rk
              valueFrom: #use Kubernetes secret for storing the password
                secretKeyRef:
                  name: domen-neon
                  key: password
          ports:
            - containerPort: 8081
              name: server
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: komentar-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8081
  selector:
    app: komentar
