kumuluzee:
  name: komentar-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/KomentarDS
      connection-url: jdbc:postgresql://ep-ancient-fog-19741782-pooler.eu-central-1.aws.neon.tech/izletnik
      username: grzin
      password: ep2sMLqtu3rk
  openapi-mp:
    enabled: true
    servlet:
      mapping: /v1/komentar/openapi
    scan:
      packages:
        - si.fri.rso.komentar.api
    ui:
      mapping: /v1/komentar/api-specs/ui
      specification-server: http://localhost:8081
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/KomentarDS
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                            <Configuration name="comments">
                                <Appenders>
                                    <Console name="console" target="SYSTEM_OUT">
                                        <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                    </Console>
                                    <Socket name="logstash" host="f4e5773d-c9f5-4519-9c8d-495ce795f5be-ls.logit.io"
                                    port="22241" protocol="udp">
                                        <JSONLayout complete="false " compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                    </Socket>
                                </Appenders>
                                <Loggers>
                                    <!-- Default logger -->
                                    <Root level="all">
                                        <AppenderRef ref="console" level="info" />
                                        <AppenderRef ref="logstash" level="trace" />
                                    </Root>
                                </Loggers>
                            </Configuration>'
  metrics:
    servlet:
      enabled: true
      mapping: /v1/komentar/metrics
  cors:
    enabled: true
    paths: "/*"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    allowed-origins: "*"
    max-age: 3600
    credentials: false
rest-properties:
  broken: false

